import{a as m,S as g,i as l}from"./assets/vendor-DQiTczw4.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const p="54715064-755e6188e76709980fdae3ed5",f="https://pixabay.com/api/";function y(s){return m.get(f,{params:{key:p,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(a=>a.data.hits).catch(a=>{console.log(a)})}const n=document.querySelector(".gallery"),c=document.querySelector(".loader");let h=new g(".gallery a",{captionsData:"alt",captionDelay:250});function L(s){const a=s.map(({webformatURL:r,largeImageURL:o,tags:e,likes:t,views:i,comments:u,downloads:d})=>`<li class = "gallery-item">
        <a href = "${o}" class="gallery-link">
        <img src = "${r}" alt = "${e}" class="gallery-images"/>
        </a>
       <ul class="data-list">
  <li class="image-data"><p class="image-data-label">Views</p><p class="image-data-text">${i}</p></li>
  <li class="image-data"><p class="image-data-label">Likes</p><p class="image-data-text">${t}</p></li>
  <li class="image-data"><p class="image-data-label">Comments</p><p class="image-data-text">${u}</p></li>
  <li class="image-data"><p class="image-data-label">Downloads</p><p class="image-data-text">${d}</p></li>
  </ul>
        </li>
        `).join("");n.insertAdjacentHTML("beforeend",a),h.refresh()}function b(){n.innerHTML=""}function S(){c.classList.remove("is-hidden")}function q(){c.classList.add("is-hidden")}const x=document.querySelector(".form"),w=document.querySelector('[name="search-text"]');function P(s){s.preventDefault();const a=w.value.trim();if(a===""){l.warning({title:"Caution",message:"Please enter a search query!",position:"topRight"});return}b(),S(),y(a).then(r=>{if(!r||r.length===0){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}L(r)}).catch(r=>{l.error({message:"Something went wrong. Try again later.",position:"topRight"}),console.error("Fetch error:",r)}).finally(()=>{q(),s.target.reset()})}x.addEventListener("submit",P);
//# sourceMappingURL=index.js.map
