import{a as m,S as g,i as o}from"./assets/vendor-B5nsgUv9.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const p="54715064-755e6188e76709980fdae3ed5",f="https://pixabay.com/api/";async function y(s){return m.get(f,{params:{key:p,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(a=>a.data.hits).catch(a=>{console.log(a)})}const n=document.querySelector(".gallery"),c=document.querySelector(".loader");let h=new g(".gallery a",{captionsData:"alt",captionDelay:250});async function L(s){const a=s.map(({webformatURL:r,largeImageURL:l,tags:e,likes:t,views:i,comments:u,downloads:d})=>`<li class = "gallery-item">
        <a href = "${l}" class="gallery-link">
        <img src = "${r}" alt = "${e}" class="gallery-images"/>
        </a>
       <ul class="data-list">
  <li class="image-data"><p class="image-data-label">Views</p><p class="image-data-text">${i}</p></li>
  <li class="image-data"><p class="image-data-label">Likes</p><p class="image-data-text">${t}</p></li>
  <li class="image-data"><p class="image-data-label">Comments</p><p class="image-data-text">${u}</p></li>
  <li class="image-data"><p class="image-data-label">Downloads</p><p class="image-data-text">${d}</p></li>
  </ul>
        </li>
        `).join("");n.insertAdjacentHTML("beforeend",a),h.refresh()}function b(){n.innerHTML=""}function S(){c.classList.remove("is-hidden")}function q(){c.classList.add("is-hidden")}const x=document.querySelector(".form"),w=document.querySelector('[name="search-text"]');async function P(s){s.preventDefault();const a=w.value.trim();if(a.length===0){o.show({title:"Warning",message:"Sorry, there are no images matching your search query. Please try again!"});return}b(),S(),y(a).then(r=>{if(r.length===0){o.show({title:"Warning",message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"red"});return}L(r)}).catch(r=>{console.error(r)}).finally(()=>{q()}),s.currentTarget.reset()}x.addEventListener("submit",P);
//# sourceMappingURL=index.js.map
